export const demo = {
  title: "Clinical Paper / component review",
  note: "Development components. These examples describe the interface, not business credentials.",
  items: [
    {
      label: "Product lines",
      href: "/products",
      detail: "Structured category navigation.",
    },
    {
      label: "Documentation",
      href: "/quality",
      detail: "Evidence before assertions.",
    },
    { label: "Trade enquiry", href: "/contact", detail: "A clear next step." },
  ],
  steps: [
    { name: "Enquiry", detail: "Define the product list." },
    { name: "Review", detail: "Review documentation requirements." },
    { name: "Contact", detail: "Agree the next step." },
  ],
  components: [
    "SplitText",
    "CountUp",
    "ScrollReveal",
    "AnimatedContent",
    "LogoLoop",
    "Magnet",
    "GradualBlur",
    "CardNav",
    "StaggeredMenu",
    "ScrollStack",
    "Stepper",
    "Masonry",
    "FlowingMenu",
    "TiltedCard",
    "Carousel",
    "Lanyard",
    "DotGrid",
  ],
  card: "Credential review card",
  status: "Verification pending",
  count: 17,
};
